### ISSUE TITLE
For `beancount` add `id` column

### ISSUE THREAD

**Issue by vikasrawal** [trevorld/r-ledger#21]
beancount has an id that uniquely identifies each entry. I think it would be helpful if the id is also imported into the data frame.

Thanks.

**Comment by trevorld** [comment]
* If `bean-query` supports this `id` then seem like it would be a straightforward addition
* A bit more reverse compatible if this was to be added as the last column in case a user was referencing columns by number instead of name?

**Comment by vikasrawal** [comment]
bean-query supports id. You just need to add "id" to the query string.
